### ISSUE TITLE
Issue with mii.py and latest litex-buildenv

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/liteeth#15]
We are getting the following error;

```
./build/arty_net_lm32/output.20180823-045832.log
---------------------------------------------
Traceback (most recent call last):
  File "./make.py", line 143, in <module>
    main()
  File "./make.py", line 108, in main
    soc = SoC(platform, ident=SoC.__name__, **soc_sdram_argdict(args), **dict(args.target_option))
  File "/home/travis/build/mithro/litex-buildenv/targets/arty/net.py", line 33, in __init__
    platform.request("eth"))
  File "/home/travis/build/mithro/litex-buildenv/third_party/liteeth/liteeth/phy/__init__.py", line 21, in LiteEthPHY
    return LiteEthPHYMII(clock_pads, pads, **kwargs)
  File "/home/travis/build/mithro/litex-buildenv/third_party/liteeth/liteeth/phy/mii.py", line 94, in __init__
    self.submodules.rx = ClockDomainsRenamer("eth_rx")(LiteEthPHYMIIRX(pads))
  File "/home/travis/build/mithro/litex-buildenv/third_party/liteeth/liteeth/phy/mii.py", line 51, in __init__
    converter.reset.eq(~pads.rx_dv),
AttributeError: 'Record' object has no attribute 'rx_dv'
```

**Comment by rohitk-singh** [comment]
Probably because arty platform has `dv` instead of `rx_dv` for ethernet? https://github.com/timvideos/litex-buildenv/blob/master/platforms/arty.py#L88-L98

**Comment by enjoy-digital** [comment]
Yes, i've changed dv to rx_dv for consistency. Can you update your platform files?

**Comment by enjoy-digital** [comment]
I just tried to do that on litex-buildenv, but i'm not able to push to the repo. Can you give me rights to do if you want me to do the change?

**Comment by mithro** [comment]
https://github.com/mithro/litex-buildenv/commit/fdbd5ed891bfbef0989b5a8261c07508a46ec680 -- Does this look right?

**Comment by enjoy-digital** [comment]
yes

**Comment by enjoy-digital** [comment]
Closing since fixed in litex-buildenv.
